### ISSUE TITLE
bold/accent guidance to enter data as percentages

### ISSUE THREAD

**Issue by jeffeaton** [mrc-ide/shiny90#71]
On the 'Upload survey data' page, can we somehow accentuate the instruction: `Estimates, Standard Error, and Lower and Upper Confidence Intervals should all be given as percentages.`

Also add an example: `Estimates, Standard Error, and Lower and Upper Confidence Intervals should all be given as percentages (for example, enter percentage 87.56 rather than proportion 0.8756).`

**Comment by r-ash** [comment]
Resolved as part of https://github.com/mrc-ide/shiny90/pull/77
