### ISSUE TITLE
iconv() fails on Côte d'Ivoire

### ISSUE THREAD

**Issue by jeffeaton** [mrc-ide/shiny90#72]
```
> iconv("Côte d'Ivoire", "UTF-8", "ASCII//TRANSLIT")
[1] "C^ote d'Ivoire"
```

Will not match to `"Cote d'Ivoire"`

**Comment by r-ash** [comment]
I'm getting a different result, in particular
```
> iconv("Côte d'Ivoire", "UTF-8", "ASCII//TRANSLIT")
[1] "Cote d'Ivoire"
```

Added a unit test
```
testthat::test_that("removeSpecialChars correctly strips special characters", {
    
    testthat::expect_equal(removeSpecialChars("Côte d'Ivoire"), "Cote d'Ivoire")
  
    testthat::expect_equal(removeSpecialChars("Togo - Centrale"), "Togo - Centrale")
    
    testthat::expect_equal(removeSpecialChars("\tMalawi\t"), "Malawi")
    
    testthat::expect_equal(removeSpecialChars("àáâãäå æ çčćž ß éĕěėëȩ öôø ùúûü"), 
                                              "aaaaaa ae cccz ss eeeeee ooo uuuu")
})
```

Which passes also. Perhaps some versioning issue?

Have you seen this not working in the app?

**Comment by r-ash** [comment]
See https://github.com/mrc-ide/shiny90/blob/i164/src/tests/unittestthat/testDataLogic.R#L82

**Comment by r-ash** [comment]
`iconv` varies across platforms which is why we're seeing different results here across machines. 

> But now that we don't have built in data, is this such an issue? the only thing is verifying that the survey and program data uploaded matches the country derived from the spectrum file. We could just enforce that the country name has to exactly match whatever comes out of spectrum. I presume the model is country agnostic, i.e. all country related data comes as an input?

Agreed to address this that we will remove the `iconv` line and revert to exact string matching.
